"""Road-mask queries used to recover a GPS route from a small off-road drift.

The Nav2 keepout filter correctly makes the road boundary non-drivable.  A
small global-localization error can nevertheless place the robot just outside
that boundary.  This module deliberately keeps the geometry side-effect free
so the goal manager can make a fail-closed recovery decision before it changes
any Nav2 runtime parameter.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from math import ceil, floor, hypot
from pathlib import Path
from typing import Optional, Tuple

import yaml


class RoadKeepoutError(ValueError):
    """The compiled road keepout artifact cannot be used safely."""


@dataclass(frozen=True)
class RoadRejoinTarget:
    """A verified short recovery target on the compiled drivable corridor."""

    x: float
    y: float
    outside_distance_m: float
    graph_distance_m: float


class RoadRejoinReason(str, Enum):
    """The explicit outcome of a road-rejoin safety evaluation."""

    REJOIN_APPROVED = "REJOIN_APPROVED"
    ALREADY_ON_ROAD = "ALREADY_ON_ROAD"
    NO_DRIVABLE_CELL_WITHIN_MARGIN = "NO_DRIVABLE_CELL_WITHIN_MARGIN"
    GRAPH_PROJECTION_TOO_FAR = "GRAPH_PROJECTION_TOO_FAR"
    GRAPH_PROJECTION_OUTSIDE_MASK = "GRAPH_PROJECTION_OUTSIDE_MASK"


@dataclass(frozen=True)
class RoadRejoinDecision:
    """A rejoin target or the precise reason it was rejected.

    All coordinates are in the route/map frame. ``nearest_mask_xy`` is the
    nearest free keepout-map cell when one exists within the configured
    margin. This deliberately gives status logs enough context to diagnose a
    rejected re-entry without scraping map pixels offline.
    """

    reason: RoadRejoinReason
    target: RoadRejoinTarget | None
    current_xy: Tuple[float, float]
    nearest_mask_xy: Tuple[float, float] | None
    nearest_road_distance_m: float | None
    graph_projection_xy: Tuple[float, float]
    graph_projection_distance_m: float

    @property
    def approved(self) -> bool:
        return self.target is not None

    @staticmethod
    def _format_xy(value: Tuple[float, float] | None) -> str:
        return "none" if value is None else "(%.2f,%.2f)" % value

    def status_fields(self) -> str:
        """Stable key order for `/gps_nav/status` and bag post-processing."""

        distance = (
            "none"
            if self.nearest_road_distance_m is None
            else f"{self.nearest_road_distance_m:.2f}"
        )
        return (
            "reason=%s; current_xy=%s; nearest_mask_xy=%s; "
            "nearest_road_distance_m=%s; graph_projection_xy=%s; "
            "graph_projection_distance_m=%.2f"
            % (
                self.reason.value,
                self._format_xy(self.current_xy),
                self._format_xy(self.nearest_mask_xy),
                distance,
                self._format_xy(self.graph_projection_xy),
                self.graph_projection_distance_m,
            )
        )


class RoadKeepoutMap:
    """Read-only view of the PGM generated by ``qgis_keepout.py``.

    The generator emits a non-negated trinary P5 PGM: 254 is road/free space
    and 0 is outside-road/lethal space.  Supporting only that explicit format
    means an unexpected hand-edited map cannot silently remove a safety
    boundary during a recovery.
    """

    def __init__(
        self,
        *,
        width: int,
        height: int,
        pixels: bytes,
        resolution: float,
        origin_x: float,
        origin_y: float,
        free_threshold: int,
    ) -> None:
        self.width = width
        self.height = height
        self.pixels = pixels
        self.resolution = resolution
        self.origin_x = origin_x
        self.origin_y = origin_y
        self.free_threshold = free_threshold

    @classmethod
    def load(cls, yaml_path: str | Path) -> "RoadKeepoutMap":
        yaml_path = Path(yaml_path).expanduser().resolve()
        try:
            metadata = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        except (OSError, yaml.YAMLError) as exc:
            raise RoadKeepoutError(f"cannot read road keepout yaml: {exc}") from exc

        if not isinstance(metadata, dict):
            raise RoadKeepoutError("road keepout yaml must contain a mapping")
        if metadata.get("mode") != "trinary" or int(metadata.get("negate", -1)) != 0:
            raise RoadKeepoutError("road keepout must be a non-negated trinary map")

        try:
            image_name = str(metadata["image"])
            resolution = float(metadata["resolution"])
            origin = metadata["origin"]
            origin_x = float(origin[0])
            origin_y = float(origin[1])
            free_threshold = int(ceil(float(metadata.get("free_thresh", 0.25)) * 255.0))
        except (KeyError, TypeError, ValueError, IndexError) as exc:
            raise RoadKeepoutError(f"invalid road keepout metadata: {exc}") from exc

        if resolution <= 0.0 or free_threshold < 0 or free_threshold > 255:
            raise RoadKeepoutError("road keepout resolution or free threshold is invalid")

        width, height, pixels = _read_binary_pgm(yaml_path.parent / image_name)
        return cls(
            width=width,
            height=height,
            pixels=pixels,
            resolution=resolution,
            origin_x=origin_x,
            origin_y=origin_y,
            free_threshold=free_threshold,
        )

    def is_drivable(self, x: float, y: float) -> bool:
        index = self._world_to_index(x, y)
        return index is not None and self.pixels[index] >= self.free_threshold

    def nearest_drivable_distance(self, x: float, y: float, max_distance_m: float) -> Optional[float]:
        """Return the nearest free-cell distance, bounded by ``max_distance_m``.

        This is used only when starting a route or recovering from a failure,
        not in the high-frequency control loop.  An exact local search avoids
        assuming the road boundary is axis-aligned.
        """

        nearest = self.nearest_drivable(x, y, max_distance_m)
        return None if nearest is None else nearest[2]

    def nearest_drivable(
        self, x: float, y: float, max_distance_m: float
    ) -> Tuple[float, float, float] | None:
        """Return nearest free-cell centre and distance within the given margin."""

        if max_distance_m <= 0.0:
            return None

        max_cells = int(ceil(max_distance_m / self.resolution)) + 1
        center_col = int(floor((x - self.origin_x) / self.resolution))
        map_y_cell = int(floor((y - self.origin_y) / self.resolution))
        center_row = self.height - 1 - map_y_cell
        best: Tuple[float, float, float] | None = None

        min_col = max(0, center_col - max_cells)
        max_col = min(self.width - 1, center_col + max_cells)
        min_row = max(0, center_row - max_cells)
        max_row = min(self.height - 1, center_row + max_cells)
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                if self.pixels[row * self.width + col] < self.free_threshold:
                    continue
                cell_x, cell_y = self._cell_center(col, row)
                distance = hypot(x - cell_x, y - cell_y)
                if distance <= max_distance_m and (
                    best is None or distance < best[2]
                ):
                    best = (cell_x, cell_y, distance)
        return best

    def _world_to_index(self, x: float, y: float) -> Optional[int]:
        col = int(floor((x - self.origin_x) / self.resolution))
        map_y_cell = int(floor((y - self.origin_y) / self.resolution))
        row = self.height - 1 - map_y_cell
        if row < 0 or row >= self.height or col < 0 or col >= self.width:
            return None
        return row * self.width + col

    def _cell_center(self, col: int, row: int) -> Tuple[float, float]:
        return (
            self.origin_x + (col + 0.5) * self.resolution,
            self.origin_y + (self.height - row - 0.5) * self.resolution,
        )


def make_road_rejoin_target(
    road_map: RoadKeepoutMap,
    current_xy: Tuple[float, float],
    graph_xy: Tuple[float, float],
    max_outside_distance_m: float,
    max_graph_distance_m: float,
) -> RoadRejoinDecision:
    """Validate a graph-edge projection as a short, safe road re-entry.

    Callers must keep the ordinary road keepout active and stop whenever the
    returned decision is not approved.
    """

    current_x, current_y = current_xy
    graph_x, graph_y = graph_xy
    graph_distance = hypot(graph_x - current_x, graph_y - current_y)
    if road_map.is_drivable(current_x, current_y):
        return RoadRejoinDecision(
            reason=RoadRejoinReason.ALREADY_ON_ROAD,
            target=None,
            current_xy=current_xy,
            nearest_mask_xy=(current_x, current_y),
            nearest_road_distance_m=0.0,
            graph_projection_xy=graph_xy,
            graph_projection_distance_m=graph_distance,
        )

    nearest = road_map.nearest_drivable(
        current_x, current_y, max_outside_distance_m
    )
    if nearest is None:
        return RoadRejoinDecision(
            reason=RoadRejoinReason.NO_DRIVABLE_CELL_WITHIN_MARGIN,
            target=None,
            current_xy=current_xy,
            nearest_mask_xy=None,
            nearest_road_distance_m=None,
            graph_projection_xy=graph_xy,
            graph_projection_distance_m=graph_distance,
        )

    nearest_x, nearest_y, outside_distance = nearest
    if graph_distance > max_graph_distance_m:
        return RoadRejoinDecision(
            reason=RoadRejoinReason.GRAPH_PROJECTION_TOO_FAR,
            target=None,
            current_xy=current_xy,
            nearest_mask_xy=(nearest_x, nearest_y),
            nearest_road_distance_m=outside_distance,
            graph_projection_xy=graph_xy,
            graph_projection_distance_m=graph_distance,
        )
    if not road_map.is_drivable(graph_x, graph_y):
        return RoadRejoinDecision(
            reason=RoadRejoinReason.GRAPH_PROJECTION_OUTSIDE_MASK,
            target=None,
            current_xy=current_xy,
            nearest_mask_xy=(nearest_x, nearest_y),
            nearest_road_distance_m=outside_distance,
            graph_projection_xy=graph_xy,
            graph_projection_distance_m=graph_distance,
        )

    target = RoadRejoinTarget(
        x=graph_x,
        y=graph_y,
        outside_distance_m=outside_distance,
        graph_distance_m=graph_distance,
    )
    return RoadRejoinDecision(
        reason=RoadRejoinReason.REJOIN_APPROVED,
        target=target,
        current_xy=current_xy,
        nearest_mask_xy=(nearest_x, nearest_y),
        nearest_road_distance_m=outside_distance,
        graph_projection_xy=graph_xy,
        graph_projection_distance_m=graph_distance,
    )


def _read_binary_pgm(path: Path) -> Tuple[int, int, bytes]:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise RoadKeepoutError(f"cannot read road keepout image: {exc}") from exc

    position = 0

    def token() -> bytes:
        nonlocal position
        while position < len(data):
            while position < len(data) and data[position] in b" \t\r\n":
                position += 1
            if position < len(data) and data[position] == ord("#"):
                while position < len(data) and data[position] not in b"\r\n":
                    position += 1
                continue
            break
        start = position
        while position < len(data) and data[position] not in b" \t\r\n#":
            position += 1
        if start == position:
            raise RoadKeepoutError("truncated PGM header")
        return data[start:position]

    try:
        magic = token()
        width = int(token())
        height = int(token())
        max_value = int(token())
    except ValueError as exc:
        raise RoadKeepoutError(f"invalid PGM header: {exc}") from exc

    if magic != b"P5" or width <= 0 or height <= 0 or max_value != 255:
        raise RoadKeepoutError("road keepout image must be an 8-bit P5 PGM")
    if position >= len(data) or data[position] not in b" \t\r\n":
        raise RoadKeepoutError("PGM header is not terminated")
    # P5 pixel data is binary.  Consume the mandatory header delimiter only;
    # scanning arbitrary whitespace here would corrupt a valid first pixel
    # whose value happens to be 0x0A, 0x0D, 0x20, or 0x09.
    if data[position] == ord("\r") and position + 1 < len(data) and data[position + 1] == ord("\n"):
        position += 2
    else:
        position += 1
    pixels = data[position:]
    if len(pixels) != width * height:
        raise RoadKeepoutError(
            f"PGM payload length {len(pixels)} does not match {width}x{height}"
        )
    return width, height, pixels
