"""Road-mask queries used to recover a GPS route from a small off-road drift.

The Nav2 keepout filter correctly makes the road boundary non-drivable.  A
small global-localization error can nevertheless place the robot just outside
that boundary.  This module deliberately keeps the geometry side-effect free
so the goal manager can make a fail-closed recovery decision before it changes
any Nav2 runtime parameter.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import ceil, floor, hypot
from pathlib import Path
from typing import Optional, Tuple

import yaml


class RoadKeepoutError(ValueError):
    """The compiled road keepout artifact cannot be used safely."""


@dataclass(frozen=True)
class RoadRejoinTarget:
    """A verified short recovery target on the compiled drivable corridor."""

    x: float
    y: float
    outside_distance_m: float
    graph_distance_m: float


class RoadKeepoutMap:
    """Read-only view of the PGM generated by ``qgis_keepout.py``.

    The generator emits a non-negated trinary P5 PGM: 254 is road/free space
    and 0 is outside-road/lethal space.  Supporting only that explicit format
    means an unexpected hand-edited map cannot silently remove a safety
    boundary during a recovery.
    """

    def __init__(
        self,
        *,
        width: int,
        height: int,
        pixels: bytes,
        resolution: float,
        origin_x: float,
        origin_y: float,
        free_threshold: int,
    ) -> None:
        self.width = width
        self.height = height
        self.pixels = pixels
        self.resolution = resolution
        self.origin_x = origin_x
        self.origin_y = origin_y
        self.free_threshold = free_threshold

    @classmethod
    def load(cls, yaml_path: str | Path) -> "RoadKeepoutMap":
        yaml_path = Path(yaml_path).expanduser().resolve()
        try:
            metadata = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        except (OSError, yaml.YAMLError) as exc:
            raise RoadKeepoutError(f"cannot read road keepout yaml: {exc}") from exc

        if not isinstance(metadata, dict):
            raise RoadKeepoutError("road keepout yaml must contain a mapping")
        if metadata.get("mode") != "trinary" or int(metadata.get("negate", -1)) != 0:
            raise RoadKeepoutError("road keepout must be a non-negated trinary map")

        try:
            image_name = str(metadata["image"])
            resolution = float(metadata["resolution"])
            origin = metadata["origin"]
            origin_x = float(origin[0])
            origin_y = float(origin[1])
            free_threshold = int(ceil(float(metadata.get("free_thresh", 0.25)) * 255.0))
        except (KeyError, TypeError, ValueError, IndexError) as exc:
            raise RoadKeepoutError(f"invalid road keepout metadata: {exc}") from exc

        if resolution <= 0.0 or free_threshold < 0 or free_threshold > 255:
            raise RoadKeepoutError("road keepout resolution or free threshold is invalid")

        width, height, pixels = _read_binary_pgm(yaml_path.parent / image_name)
        return cls(
            width=width,
            height=height,
            pixels=pixels,
            resolution=resolution,
            origin_x=origin_x,
            origin_y=origin_y,
            free_threshold=free_threshold,
        )

    def is_drivable(self, x: float, y: float) -> bool:
        index = self._world_to_index(x, y)
        return index is not None and self.pixels[index] >= self.free_threshold

    def nearest_drivable_distance(self, x: float, y: float, max_distance_m: float) -> Optional[float]:
        """Return the nearest free-cell distance, bounded by ``max_distance_m``.

        This is used only when starting a route or recovering from a failure,
        not in the high-frequency control loop.  An exact local search avoids
        assuming the road boundary is axis-aligned.
        """

        if max_distance_m <= 0.0:
            return None

        max_cells = int(ceil(max_distance_m / self.resolution)) + 1
        center_col = int(floor((x - self.origin_x) / self.resolution))
        map_y_cell = int(floor((y - self.origin_y) / self.resolution))
        center_row = self.height - 1 - map_y_cell
        best = None

        min_col = max(0, center_col - max_cells)
        max_col = min(self.width - 1, center_col + max_cells)
        min_row = max(0, center_row - max_cells)
        max_row = min(self.height - 1, center_row + max_cells)
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                if self.pixels[row * self.width + col] < self.free_threshold:
                    continue
                cell_x, cell_y = self._cell_center(col, row)
                distance = hypot(x - cell_x, y - cell_y)
                if distance <= max_distance_m and (best is None or distance < best):
                    best = distance
        return best

    def _world_to_index(self, x: float, y: float) -> Optional[int]:
        col = int(floor((x - self.origin_x) / self.resolution))
        map_y_cell = int(floor((y - self.origin_y) / self.resolution))
        row = self.height - 1 - map_y_cell
        if row < 0 or row >= self.height or col < 0 or col >= self.width:
            return None
        return row * self.width + col

    def _cell_center(self, col: int, row: int) -> Tuple[float, float]:
        return (
            self.origin_x + (col + 0.5) * self.resolution,
            self.origin_y + (self.height - row - 0.5) * self.resolution,
        )


def make_road_rejoin_target(
    road_map: RoadKeepoutMap,
    current_xy: Tuple[float, float],
    graph_xy: Tuple[float, float],
    max_outside_distance_m: float,
    max_graph_distance_m: float,
) -> Optional[RoadRejoinTarget]:
    """Validate a graph-edge projection as a short, safe road re-entry.

    ``None`` means recovery is unsafe or unnecessary.  Callers must keep the
    ordinary road keepout active and stop rather than trying to cross an
    unknown amount of non-road space.
    """

    current_x, current_y = current_xy
    if road_map.is_drivable(current_x, current_y):
        return None

    outside_distance = road_map.nearest_drivable_distance(
        current_x, current_y, max_outside_distance_m
    )
    if outside_distance is None:
        return None

    graph_x, graph_y = graph_xy
    graph_distance = hypot(graph_x - current_x, graph_y - current_y)
    if graph_distance > max_graph_distance_m or not road_map.is_drivable(graph_x, graph_y):
        return None

    return RoadRejoinTarget(
        x=graph_x,
        y=graph_y,
        outside_distance_m=outside_distance,
        graph_distance_m=graph_distance,
    )


def _read_binary_pgm(path: Path) -> Tuple[int, int, bytes]:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise RoadKeepoutError(f"cannot read road keepout image: {exc}") from exc

    position = 0

    def token() -> bytes:
        nonlocal position
        while position < len(data):
            while position < len(data) and data[position] in b" \t\r\n":
                position += 1
            if position < len(data) and data[position] == ord("#"):
                while position < len(data) and data[position] not in b"\r\n":
                    position += 1
                continue
            break
        start = position
        while position < len(data) and data[position] not in b" \t\r\n#":
            position += 1
        if start == position:
            raise RoadKeepoutError("truncated PGM header")
        return data[start:position]

    try:
        magic = token()
        width = int(token())
        height = int(token())
        max_value = int(token())
    except ValueError as exc:
        raise RoadKeepoutError(f"invalid PGM header: {exc}") from exc

    if magic != b"P5" or width <= 0 or height <= 0 or max_value != 255:
        raise RoadKeepoutError("road keepout image must be an 8-bit P5 PGM")
    if position >= len(data) or data[position] not in b" \t\r\n":
        raise RoadKeepoutError("PGM header is not terminated")
    # P5 pixel data is binary.  Consume the mandatory header delimiter only;
    # scanning arbitrary whitespace here would corrupt a valid first pixel
    # whose value happens to be 0x0A, 0x0D, 0x20, or 0x09.
    if data[position] == ord("\r") and position + 1 < len(data) and data[position + 1] == ord("\n"):
        position += 2
    else:
        position += 1
    pixels = data[position:]
    if len(pixels) != width * height:
        raise RoadKeepoutError(
            f"PGM payload length {len(pixels)} does not match {width}x{height}"
        )
    return width, height, pixels
