"use strict";
const $=id=>document.getElementById(id);
const modeLabels={VIEW_ONLY:"只读观察",READY:"任务就绪 / 等待启动",AUTONOMOUS:"研究任务已请求",PAUSED:"任务暂停",TAKEOVER_WAIT:"等待现场人工接管",STOP_LATCHED:"软件停止已锁存"};
const windowId=crypto.randomUUID();
let csrf="",state=null,online=false,toastTimer;
function toast(message,error=false){$("toast").textContent=message;$("toast").className=error?"error":"";$("toast").style.display="block";clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").style.display="none",6000);}
async function command(action,payload={}){try{const response=await fetch("/api/command",{method:"POST",headers:{"Content-Type":"application/json","X-Console-CSRF":csrf,"X-Console-Window":windowId},body:JSON.stringify({action,payload,request_id:crypto.randomUUID()})});const result=await response.json();if(action!=="heartbeat")toast(result.reason,!result.accepted);if(!response.ok&&action==="heartbeat")online=false;await poll();return result;}catch{online=false;toast("连接中断；系统将撤销操作员许可",true);}}
function options(id,rows,selected){const element=$(id),old=element.value;if(JSON.stringify(rows.map(r=>r[0]))===element.dataset.ids)return;element.replaceChildren(...rows.map(([value,label])=>{const o=document.createElement("option");o.value=value;o.textContent=label;return o;}));element.dataset.ids=JSON.stringify(rows.map(r=>r[0]));element.value=rows.some(r=>r[0]===old)?old:(selected||rows[0]?.[0]||"");}
function fresh(name,age=.5){const input=state?.inputs?.[name];return input&&input.age_s<=age?input.value:null;}
function render(){if(!state)return;$("connection").textContent=online?"ROS 界面在线":"连接中断";$("connection").className="pill "+(online?"":"danger");$("environment").textContent=state.mode.toUpperCase();$("actuator").textContent=state.actuator_enabled?"执行器：启动配置已启用":"执行器：禁用";$("actuator").className="pill "+(state.actuator_enabled?"danger":"muted");$("mode-title").textContent=modeLabels[state.state]||state.state;$("mode-reason").textContent=state.reason;$("claim").textContent=state.owns_lease?"当前操作席":state.lease_active?"其他窗口操作中":"接管操作席";$("claim").disabled=state.owns_lease||state.lease_active;
const controls=["reset","start","pause","takeover","stop","task-select","replay-start","replay-pause","replay-resume","replay-stop"];controls.forEach(id=>$(id).disabled=!online||!state.owns_lease);$("start").disabled||=state.state!=="READY"||state.blocked.length>0;$("reset").disabled||=!state.stop_confirmed_from_odom;$("task-select").disabled||=state.state==="AUTONOMOUS"||state.task.node_ids.length<2;["replay-start","replay-pause","replay-resume","replay-stop"].forEach(id=>$(id).disabled||=state.mode!=="replay"||state.actuator_enabled);$("replay-start").disabled||=state.replay.bags.length===0||["PLAYING","PAUSED"].includes(state.replay.state);$("replay-pause").disabled||=state.replay.state!=="PLAYING";$("replay-resume").disabled||=state.replay.state!=="PAUSED";$("replay-stop").disabled||=!["PLAYING","PAUSED"].includes(state.replay.state);
$("blockers").replaceChildren(...state.blocked.map(reason=>{const li=document.createElement("li");li.textContent=reason;return li;}));$("ready-summary").textContent=state.blocked.length?`${state.blocked.length} 项阻塞；保持停车` :"任务请求条件已齐备；实际轨迹仍须通过末端检查";$("still").textContent=state.stop_confirmed_from_odom?"测量静止已确认 · 不代表物理制动验收":"等待测量静止确认";
const odom=fresh("odom",.2);$("velocity").textContent=odom?`${odom.v.toFixed(3)} m/s · ${odom.w.toFixed(3)} rad/s`:"— / 过期";$("rtk").textContent=fresh("rtk_mode")||"UNKNOWN / 过期";$("lio").textContent=fresh("health")||"UNKNOWN / 过期";$("tracker").textContent=fresh("tracker")?.state||"未连接 / 过期";$("tracker").title=fresh("tracker")?.reason||"";$("map-version").textContent="odom · "+(fresh("map_version")||"地图版本未知 / 过期");options("task-start",state.task.node_ids.map(id=>[id,id]),state.task.start_node);options("task-goal",state.task.node_ids.map(id=>[id,id]),state.task.goal_node);$("task-state").textContent=state.task.accepted?"已确认":"未就绪";$("task-reason").textContent=state.task.reason;options("bag",state.replay.bags.map(b=>[b.id,b.label+` · ${b.duration_s.toFixed(1)} s`]));$("replay-state").textContent=state.replay.state;$("replay-reason").textContent=state.replay.reason;
$("events").replaceChildren(...state.events.slice().reverse().map(e=>{const li=document.createElement("li"),t=document.createElement("time");t.textContent=new Date(e.time*1000).toLocaleTimeString();li.append(t,document.createTextNode((modeLabels[e.state]||e.state)+" · "+e.reason));return li;}));draw();}
function draw(){const canvas=$("map"),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const odom=fresh("odom",.2),grid=fresh("grid_display"),permission=fresh("permission_display"),radius=Number($("zoom").value);$("map-empty").style.display=odom&&grid?"none":"flex";const cx=odom?.x||0,cy=odom?.y||0,scale=Math.min(w,h)/(radius*2),px=x=>w/2+(x-cx)*scale,py=y=>h/2-(y-cy)*scale;
ctx.strokeStyle="#21343e";ctx.lineWidth=1;for(let i=-radius;i<=radius;i++){ctx.beginPath();ctx.moveTo(px(cx+i),0);ctx.lineTo(px(cx+i),h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,py(cy+i));ctx.lineTo(w,py(cy+i));ctx.stroke();}
function paintGrid(g,isPermission){if(!g)return;for(let y=0;y<g.height;y++)for(let x=0;x<g.width;x++){const v=g.cells[y*g.width+x];if(isPermission&&v===0)continue;ctx.fillStyle=isPermission?"#be7b5355":v<0?"#25323a":v>=50?"#bc695c":"#324b4d";ctx.fillRect(px(g.x+x*g.resolution),py(g.y+(y+1)*g.resolution),g.resolution*scale+.3,g.resolution*scale+.3);}}paintGrid(grid,false);paintGrid(permission,true);
function line(points,color){if(!points?.length)return;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(px(x),py(y)):ctx.moveTo(px(x),py(y)));ctx.lineWidth=2;ctx.strokeStyle=color;ctx.stroke();}line(fresh("road")?.points,"#e2c593");const trajectory=fresh("trajectory");if(trajectory&&trajectory.map_version===fresh("map_version"))line(trajectory.points,"#b8eccd");const e=fresh("road_event");if(e){ctx.beginPath();ctx.arc(px(e.x),py(e.y),6,0,2*Math.PI);ctx.strokeStyle="#e7bd7c";ctx.stroke();}if(odom){ctx.save();ctx.translate(px(odom.x),py(odom.y));ctx.rotate(-odom.yaw);ctx.fillStyle="#edf7fa";ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-7,7);ctx.lineTo(-4,0);ctx.lineTo(-7,-7);ctx.closePath();ctx.fill();ctx.restore();}ctx.fillStyle="#93aab6";ctx.font="10px system-ui";ctx.fillText(`${radius*2} m 视野 · odom · 显示网格经过降采样`,12,20);}
async function poll(){try{const r=await fetch("/api/state",{cache:"no-store",headers:{"X-Console-Window":windowId}});if(!r.ok)throw Error();state=await r.json();online=true;}catch{online=false;}render();}
$("claim").onclick=()=>command("claim");["reset","start","pause","takeover","stop"].forEach(id=>$(id).onclick=()=>command(id));$("task-select").onclick=()=>command("task",{start_node:$("task-start").value,goal_node:$("task-goal").value});["start","pause","resume","stop"].forEach(action=>$("replay-"+action).onclick=()=>command("replay_"+action,action==="start"?{bag_id:$("bag").value}:{}));$("zoom").oninput=draw;window.addEventListener("resize",draw);document.addEventListener("keydown",e=>{if(e.key==="Escape"&&state?.owns_lease)command("stop");});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state?.owns_lease&&state.state==="AUTONOMOUS")command("pause");});
(async()=>{try{csrf=(await(await fetch("/api/session")).json()).csrf;await poll();}catch{toast("无法连接研究后端",true);}setInterval(poll,250);setInterval(()=>{if(state?.owns_lease&&!document.hidden)command("heartbeat");},200);})();
